name: 'Release'
on:
  push:
    branches:
      - main
jobs:
  Update_Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Codes'
        uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Build'
        run: |
          npm ci
          npm run build --if-present
          mv dist hotaru-theme
          zip -r -9 hotaru-theme.zip ./hotaru-theme

      - name: 'Release'
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
